### ISSUE TITLE
!sleeper-subscribe does not seem to be working

### ISSUE THREAD

**Issue by red-scott** [christytc10/sleeper-discord-events#10]
After typing

```!sleeper-subscribe 862103738540744704```

I waited an hour and got no response.

I tried 

```!sleeper-unsubscribe 862103738540744704```

To see if that would output a message and no such luck

**Comment by christytc10** [comment]
Hi. Thanks for raising this, it should be fixed now. Could you try again?

There was an influx of new leagues added and I really hadn't cover some edge cases (commish force adds and picks for picks trades with no players moving). These caused the app to crash, should be up now

**Comment by red-scott** [comment]
Thanks, sleeper-subscribe worked successfully!
