### ISSUE TITLE
"Already subscribed" when trying to add league

### ISSUE THREAD

**Issue by kevinxu118** [christytc10/sleeper-discord-events#3]
Instead of getting "Subscribed to league YourleagueName" when running `!sleeper-subscribe [leagueID]`, the bot says "Already subscribed. Please run !sleeper-unsubscribe first if you want to change the league this channel is subscribed to", instead of "Subscribed to league YourleagueName".

![image](https://user-images.githubusercontent.com/42543903/133854231-400027ce-f54a-4a5a-a206-3c223ad8b359.png)

**Comment by nickbalto** [comment]
Getting the same message on my channel and then had a transaction today that did not come through. Have unsubscribed and resubscribed but still receive "Already Subscribed"

**Comment by christytc10** [comment]
Thanks for raising this. It should be fixed now, could you retry @nickbalto / @kevinxu118

**Comment by kevinxu118** [comment]
Seems to work now, waiting to see if transactions come through.
